---
######################################
# Click on "Run Document" in RStudio #
######################################
title: "ABC with Random Forests"
author: "Miguel de Navascués"
output: learnr::tutorial
runtime: shiny_prerendered
bibliography: references.bib
---

These learning resources are available at [GitHub](https://github.com/mnavascues/ABCRFtutorial) & [Zenodo](http://doi.org/10.5281/zenodo.1435503).

## Setup (tl;dr)

```{r setup, include=TRUE}
library(learnr)
# functions for ABCRF
library(abcrf)
# function for weighted histogram
suppressMessages(library(weights, quietly=T))
# functions for CARTs
library(tree)
```

## Classification and regression tree

Random forests are a machine learning method for regression and classification. Its name comes from the fact of being constituted of "trees". These trees are classification and regression trees or CARTs.
xxxxxx

### Exercise 1

xxxx

```{r cart, exercise=TRUE, exercise.lines=30}
target    <- readRDS(file="/home/miguel/Work/Teaching/ABCRF tutorial/target.RDS")
ref_table <- readRDS(file="/home/miguel/Work/Teaching/ABCRF tutorial/ref_table_2.RDS")


head(ref_table)
#regression_tree <- tree(theta ~ TD + PI, data=ref_table)



```
